# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - courtbook-rest

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  NODE_VERSION: '22.x'
  WORKING_DIRECTORY: ./apps/api

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: ${{ env.WORKING_DIRECTORY }}/package-lock.json

      - name: Install dependencies
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: npm ci

      - name: Build application
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: npm run build

      - name: Prepare deployment files
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: |
          npm prune --production
          # Create .deployment file for Azure
          echo "[config]" > .deployment
          echo "SCM_DO_BUILD_DURING_DEPLOYMENT=false" >> .deployment

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: ${{ env.WORKING_DIRECTORY }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app
          path: ./deployment

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_C1A521D73F8148CC8C8641C34A87365B }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_55A4DB056A744668B483070F53971112 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_98CDEE2F8AA94234B53B1A096CBD5941 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'courtbook-rest'
          slot-name: 'Production'
          package: ./deployment
          startup-command: 'npm run start'

      - name: Check deployment health
        run: |
          echo "Waiting for application to start..."
          sleep 30
          response=$(curl -s -o /dev/null -w "%{http_code}" https://courtbook-rest.azurewebsites.net/ || echo "000")
          if [ "$response" = "200" ]; then
            echo "✅ Application is healthy"
          else
            echo "❌ Health check failed with status: $response"
            exit 1
          fi
          