# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - courtbook

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  NODE_VERSION: '22.x'
  WORKING_DIRECTORY: ./apps/web

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: ${{ env.WORKING_DIRECTORY }}/package-lock.json

      - name: Install dependencies for Web
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: npm ci

      - name: Build Web (Vite + React)
        working-directory: ${{ env.WORKING_DIRECTORY }}
        env:
          VITE_API_URL: ${{ secrets.VITE_API_URL }}
        run: npm run build

      - name: Create production package.json
        working-directory: ${{ env.WORKING_DIRECTORY }}/dist
        run: |
          echo '{
            "name": "courtbook-web",
            "version": "1.0.0",
            "scripts": {
              "start": "npx serve -s . -p ${PORT:-8080}"
            }
          }' > package.json

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: ${{ env.WORKING_DIRECTORY }}/dist

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app
          path: ./deployment

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_0B09F561A2C4448EB87D727780420D07 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_6EC6A3AE688F494998153DFB54146715 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_6FB1CCE482C046C7B7BEE8F359739166 }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'courtbook'
          slot-name: 'Production'
          package: ./deployment
          